### ISSUE TITLE
[proposal] Custom truncation configuration

### ISSUE THREAD

**Issue by liqueurdetoile** [vierge-noire/cakephp-test-suite-light#19]
@pabloelcolombiano Hi,

I've spent some time to look deeper in code and to think about what can be interesting to do.

First of all, why tuning truncation above what can be done now ? Here's some use cases I've imagined :

Example 1 : You're focusing on few tests when writing down some code and you don't care about database state. You want the tests to run fast, so disabling all truncation setup and operations is a way to go. It must be quick and simple to do it and I think using environment is a great deal as it is not coupled with code. Im y opnion, it is better than overriding app configuration as it can be done through a wrapper script and avoid the *damn, I forgot to turn it off and it ruins my CI/CD run* when pushing to repository. It's also easy to set it up in PHPUnit configuration or test bootstrap. Anyway, it can crossed with a app configuration setting (e.g. `Configure::write('CakephpTestSuiteLight.<thekey>', true)` in test bootstrap).

Example 2: You're dealing with two databases and one is mainly here to provide data, expect in a very few tests that inserts some data in dummy tables. There is no way now to tune truncation at runtime for a specific connection (e.g. disable it as default and enable it in a single test case). Okay, we're nearly reached Wonderland issue here 😄 

The goal is to provide a way for the dev to adjust truncation at will.

This is what I propose :

- Keep defaults as by now : dirty tables are truncated before each tests except for ignored connections configured in datasources. It will surely help to avoid backwards compatibility issues.

- Check for a `CTSL_DISABLE_TRUNCATION` in environnement that can be settled by the dev if it chooses so before launching tests. If found, all truncation setup is skipped and no truncations are ever done. 

- Check for a `CTSL_SKIP_TRUNCATION` in environnement that can be settled by the dev if it chooses so before launching tests to invert default behavior. Truncation setup is done but truncations only occurs if requested (see below)

- Use the `SkipTablesTruncation` trait and add its counterpart `ForceTablesTruncation` to allow overriding global setting per test case for all connections

- Check for `CTSL_SKIP_TRUNCATION=<connection1>[,<connection2>,...]` and `CTSL_FORCE_TRUNCATION=<connection1>[,<connection2>,...]` to evaluate per **non-ignored** connections if truncation should be done in the connection. It overrides global setting and traits.

- Add a `TunerTrait` helper that can be used in test case to bring convenient methods to update previous vars within test runtime (e.g `enableAllTruncations`, `disableAllTruncations`, `disableTruncation(connection1, connection2...)`, `enableTruncation(connection1, connection2...)`

Obviously, tuning per connection is really a huge edge case and I'm not really sure it should be implemented if not requested.

What do you think about that ?

**Comment by pabloelcolombiano** [comment]
Hi @liqueurdetoile,

this is a very interesting enhancement.

1. Agreed. Truncating tables if no tables were modified is very cheap. Since the dirty tables collector is empty, no truncation takes place.
2. I agree, that for some projects with large parts not interacting with the DB, this can be interesting.
3. Agreed.
4. Agreed.
5. Agreed.
6. Agreed. I would name that trait `TablesTruncationTrait`. The `disableTruncation` method would return a string or an array of strings with all the connections to be skipped.

The `FixtureInjectorSkipTruncationTest` should accordingly be extended to cover all cases. Documentation should be enhanced too.

This sounds like a very sound enhancement. Feel free to propose a PR!  

I agree with all approaches, apart maybe the last `TunerTrait`, that might turn things too

**Comment by liqueurdetoile** [comment]
Thanks for reply and enthusiasm 😃 

I'll work on it asap.
