### ISSUE TITLE
Automatic Truncate not working with different datasource Tables

### ISSUE THREAD

**Issue by maidzen** [vierge-noire/cakephp-test-suite-light#48]
i have multiple Tables. some on Datasource "default" and some on datasource "logs".

The fixture factory works as expected on the unit test for Datasource Default tables.
But on the tables with different datasource entries get not truncated after Test execution.

i use CakePHP 4.2.8 and fixture-factories 2.3.1

If i can provide any helpful data or Code snips. Please let me know

**Comment by pabloelcolombiano** [comment]
What is the name of the test connection for the logs? Do your have a test_logs connection, for example?
Or do your tests write in the "logs" connection?

Only "test" and "test_*" connections get truncated. If you need, I can introduce a flag to enable a connection to be truncated by the suite as well.

**Comment by maidzen** [comment]
the datasource for the tests is called  'test_logs'
the datasource are defined as 

```
        'test' => [
            'host' => 'removed',
            'username' => 'removed',
            'password' => 'removed',
            'database' => 'testranet_test', // FixtureFactory
            'quoteIdentifiers' => true,
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Mysql',
            'url' => env('DATABASE_TEST_URL', null),
        ],
        'test_logs' => [
            'host' => 'removed',
            'username' => 'removed',
            'password' => 'removed',
            'database' => 'testranet_test', // FixtureFactory
            'className' => 'Cake\Database\Connection',
            'quoteIdentifiers' => true,
            'driver' => 'Cake\Database\Driver\Mysql',
            'url' => env('DATABASE_TEST_URL', null),
        ],
```

**Comment by maidzen** [comment]
> is this a problem (same DB for both) ?

i tested it and yes its the problem. we can ensure tablenames are uniqe across both DBs so we thought this should not be a problem

maybe you consider this a bug so i don't close it but if you not feel free to see this as solved. Thank you

**Comment by pabloelcolombiano** [comment]
If `test` and `test_logs` point to the same DB, I do not see why the logs did not get truncated. According to your example, I would expect that since both connection have the same schema, triggers ([see here](https://github.com/vierge-noire/cakephp-test-suite-light/blob/main/src/Sniffer/MysqlTriggerBasedTableSniffer.php#L56)) get created twice, which would generate a (silent?) error.

In your case, I would simply ignore the truncation of the `test_logs` connection, since `test` is already being handled. [Here](https://github.com/vierge-noire/cakephp-test-suite-light#ignoring-connections) is explained how to.

I do not think this is a bug. Let me know if this existing solution (skipping truncation in `test_logs`) solved your issue.
