### ISSUE TITLE
PostgresTriggerBasedTableSniffer Postgres Version

### ISSUE THREAD

**Issue by toby2g** [vierge-noire/cakephp-test-suite-light#56]
Not sure if this is the right place to raise it, but the SQL outlined in the `PostgresTriggerBasedTableSniffer.php` file is targeted towards more recent versions of Postgres.

`CALL` looks to be introduced in Postgres 11 

e.g. `$connection->execute('CALL TruncateDirtyTables();');`

`CREATE OR REPLACE PROCEDURE` also looks to be introduced in Postgres 11.

e.g. `$this->getConnection()->execute("
            CREATE OR REPLACE PROCEDURE TruncateDirtyTables() AS $$`

**Comment by pabloelcolombiano** [comment]
@toby2g thank you for the report. This is indeed the right place to discuss the issue. I see here the following options:

1. Require users to use Postgres version <= 11 since Postgres 10 end of life [is scheduled for November](https://www.postgresql.org/support/versioning/).
2. Require (from you?) a PR to make Postgres 10 compatible.

What do you think?

**Comment by toby2g** [comment]
PR created. #57
